name: Build

on:
  - push

jobs:
  changes:
    name: "Check for docs changes"
    runs-on: ubuntu-latest
    outputs:
      developers-site: ${{ steps.filter.outputs.developers-site }}
      klexhealth: ${{ steps.filter.outputs.klexhealth }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.4.2
        id: filter
        with:
          filters: |
            developers-site:
              - 'developers.cloudflare.com/**'
            klexhealth:
              - 'products/klexhealth/**'
            support-pp:
              - 'products/support-pp/**'

  build-developers-site:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.developers-site == 'true' }}
    defaults:
      run:
        shell: bash
        working-directory: "developers.cloudflare.com"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          npm run build

  build-klexhealth:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.klexhealth == 'true' }}
    defaults:
      run:
        shell: bash
        working-directory: products/klexhealth
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          mkdir .docs
          npm run ghactionsbootstrap
          npm run build
  build-support-pp:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.support-pp == 'true' }}
    defaults:
      run:
        shell: bash
        working-directory: products/support-pp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          mkdir .docs
          npm run ghactionsbootstrap
          npm run build
